### ISSUE TITLE
Error Cannot find module './tables'

### ISSUE THREAD

**Issue by lucasmm96** [Voakie/ebcdic-ascii#4]
Hi, this is my code: 

```
const EBCDIC = require("ebcdic-ascii");

const converter = new EBCDIC("0037")

converter.toASCII("E385A2A340D485A2A2818785")
// returns "Test Message"

converter.toEBCDIC("54657374204D657373616765")
// returns "E385A2A340D485A2A2818785"
```

I got this error: 
```
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module './tables'
Require stack:
- /Users/lucasmm/Downloads/node2z/node_modules/ebcdic-ascii/out/index.js
```

Any idea to fix it?

**Comment by Voakie** [comment]
My guess is that the package does not work with the old `require()` syntax. In any case I would advise using ES Imports like in the Readme: `import EBCDIC from "ebcdic-ascii"`

Let me know if that fixes the issue

**Comment by chiky123ser** [comment]
hello good afternoon I have the same error

I am using `import EBCDIC from "ebcdic-ascii"` in nodejs 18

I solved it by going back to version 1.1.0

**Comment by Voakie** [comment]
@lucasmm96 @chiky123ser The issue should be fixed in version 1.1.2, can you confirm?

**Comment by lucasmm96** [comment]
I am using `Node.js v18.16.0` and `"ebcdic-ascii": "^1.1.2"`

I tested using `require` and `import`. I got this error:
```
const converter = new EBCDIC("0037")
                  ^
TypeError: EBCDIC is not a constructor
```

**Comment by Voakie** [comment]
> I tested using `require` and `import`.

Make sure to import the module correctly (with `.default`):
```js
const EBCDIC = require("ebcdic-ascii").default
```

I updated the README to clarify this step

**Comment by lucasmm96** [comment]
Now it worked. Thank you!
